name: movie_streaming_app

description: "A new Flutter project."

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  intl: ^0.20.2
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_screenutil: ^5.9.3
  flutter_easyloading: ^3.0.5
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  iconsax: ^0.0.8
  get: ^4.6.6
  web_socket_channel: ^3.0.1
  json_annotation: ^4.9.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  video_player: ^2.9.2
  chewie: ^1.7.4
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue-Roman.otf
          weight: 400
        - asset: assets/fonts/HelveticaNeue-Light.otf
          weight: 300
        - asset: assets/fonts/HelveticaNeue-Medium.otf
          weight: 500
        - asset: assets/fonts/HelveticaNeue-Bold.otf
          weight: 700
        - asset: assets/fonts/HelveticaNeue-Thin.otf
          weight: 100
      
    
